DROP TABLE IF EXISTS `lng_lonum`;
CREATE TABLE `lng_lonum` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `step` int(11) NOT NULL COMMENT 'Which step the user left off on',
  `method` char(1) COLLATE utf8_unicode_ci DEFAULT 'N' COMMENT 'N=New Generated Course, M=Manually Input Course, V=New Version of Existing Course',
  `type` char(1) COLLATE utf8_unicode_ci DEFAULT 'P' COMMENT 'C=Course (ILT/VILT), P=Product (WBT, CBT, Other)',
  `delv_type` char(1) COLLATE utf8_unicode_ci DEFAULT 'W' COMMENT 'I=instructor led event (course), V=virtual event (course), W=online class (wbt), T=test, E=exam, A=assessment, S=survey, K=curriculum/package, D=video, M=material',
  `catdiv_id` bigint(20) DEFAULT NULL COMMENT 'foreign key referencing alu_ple_lms_course_gen_catdiv table',
  `owner_id` bigint(20)  DEFAULT NULL COMMENT 'foreign key referencing um_user table',
  `course_no` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `course_no_raw` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Course Number with the version info stripped off the end',
  `version` varchar(255) COLLATE utf8_unicode_ci DEFAULT '1.0',
  `course_title` varchar(512) COLLATE utf8_unicode_ci DEFAULT NULL,
  `product_relnum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `course_duration` float DEFAULT NULL COMMENT 'Stored in DB as minutes, but displayed usually in hours',
  `course_level` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `available` char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `published_to_lms` char(1) COLLATE utf8_unicode_ci DEFAULT 'N' COMMENT 'Y=Yes, N=No',
  `csod_loid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'CSOD LOID (UUID)',
  `updated_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inserted_on` datetime DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `xs_unq_lms_course_gen1` (`course_no`,`version`),
  UNIQUE KEY `xs_unq_lms_course_gen2` (`course_no_raw`,`version`),
  KEY `type` (`type`),
  KEY `delv_type` (`delv_type`),
  KEY `catdiv_id` (`catdiv_id`),
  KEY `owner_id` (`owner_id`),
  KEY `course_no` (`course_no`),
  KEY `course_no_raw` (`course_no_raw`),
  KEY `version` (`version`),
  KEY `published_to_lms` (`published_to_lms`),
  KEY `csod_loid` (`csod_loid`),
  KEY `step` (`step`),
  CONSTRAINT `fk_lng_lonum_cdiv` FOREIGN KEY (`catdiv_id`) REFERENCES `lng_lonum_catdiv` (`id`),
  CONSTRAINT `fk_lng_lonum_own_id` FOREIGN KEY (`owner_id`) REFERENCES `lng_users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5000 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT 'This is the main LO Number Generator Table';
